main: net.nunnerycode.bukkit.ivory.IvoryPlugin
version: ${project.build.version}
name: ${project.build.name}
author: ToppleTheNun

commands:
  displayitem:

permissions:
  ivory.displayitem:
    default: true